ZUMART/urls.py
from django.urls import path, include
from django.contrib import admin
from django.urls import path

"""
URL configuration for ZUMART project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
    
]

main/urls.py
from django.urls import path
from main.views import show_main, create_item, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user, edit_item, delete_item, get_item_json, add_item_ajax, create_product_flutter
from . import views

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-item', create_item, name='create_item'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-item/<int:id>', edit_item, name='edit_item'),
    path('delete/<int:id>', delete_item, name='delete_item'),
    path('get-item-json/', get_item_json, name='get_item_json'),
    path('add-item-ajax/', add_item_ajax, name='add_item_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Items(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    color = models.CharField(max_length=255)
    amount = models.IntegerField()
    price = models.IntegerField(default=1000000)  
    size = models.IntegerField(default=38)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

main/forms.py
from django.forms import ModelForm
from main.models import Items

class ItemForm(ModelForm):
    class Meta:
        model = Items
        fields = ["name", "size", "color", "amount", "price", "description"] 

main/views.py
import datetime
import json
from django.shortcuts import render
from .models import Items
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound, JsonResponse
from main.forms import ItemForm
from django.urls import reverse
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib import messages  
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt


@login_required(login_url='/login')

def show_main(request):
    items = Items.objects.filter(user=request.user)
    item_count = items.count()
    context = {
        'name': request.user.username,
        'kelas' : 'PBP C',
        'items' : items,
        'item_count': item_count,
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "main.html", context)

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        Items = form.save(commit=False)
        Items.user = request.user
        Items.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_item.html", context)

def show_xml(request):
    data = Items.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Items.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Items.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Items.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_item(request, id):
    item = Items.objects.get(pk = id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_item.html", context)

def delete_item(request, id):
    item = Items.objects.get(pk = id)
    item.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

def get_item_json(request):
    items_item = Items.objects.all()
    return HttpResponse(serializers.serialize('json', items_item))

@csrf_exempt
def add_item_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        price = request.POST.get("price")
        description = request.POST.get("description")
        user = request.user
        color = request.POST.get("color")
        amount = request.POST.get("amount")
        size = request.POST.get("size")

        new_item = Items(name=name, price=price, description=description, user=user, color=color,amount=amount, size=size )
        new_item.save()

        return HttpResponse(b"CREATED", status=201)
        
    return HttpResponseNotFound()

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Items.objects.create(
            user = request.user,
            name = data["name"],
            price = int(data["price"]),
            description = data["description"],
            amount = int(data["amount"])

        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_item.html
{% extends 'base.html' %}

{% block content %}

<style>

    body {
        background: linear-gradient(135deg,#0004ff, #ffffff);
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    
    .content-container {
        text-align: center;
        background: rgba(255, 255, 255, 0.95);
        box-shadow: 0 5px 15px rgba(0, 0, 0, 0.3);
        border-radius: 10px;
        padding: 20px;
        width: 80%;
        max-width: 800px;
        max-height: 80vh; 
        overflow-y: auto; 
    }

    h1 {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        color: #0004ff;
        font-weight: 560;
        font-size: 38px;
    }

    p {
        color: #333;
        font-size: 18px;
        margin-top: 20px;
    }

\    form {
        width: 100%;
        max-width: 600px;
        margin: 0 auto;
        padding: 20px;
    }

    table {
        width: 100%;
        border-collapse: collapse;
    }

    th, td {
        padding: 10px;
        text-align: left;
        border-bottom: 1px solid rgb(255, 255, 255);
    }

    th {
        background-color: #0004ff;
        color: #fff;
    }

    input[type="text"], input[type="number"] {
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid rgb(255, 255, 255);
        border-radius: 5px;
        background-color: #ffffff;
        color: #333;
        font-size: 16px;
    }

    input[type="submit"] {
        background-color: #0004ff;
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
        font-size: 18px;
        transition: background-color 0.3s ease;
    }

    input[type="submit"]:hover {
        background-color: #0004ff; 
    }
</style>

<div class="content-container">
    <h1>Add your shoes !</h1>

    <form method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr>
                <td></td>
                <td>
                    <input type="submit" value="Add Product"/>
                </td>
            </tr>
        </table>
    </form>
</div>

{% endblock %}

main/templates/edit_item.html
{% extends 'base.html' %}

{% block content %}

<style>
    body {
        background: linear-gradient(135deg, #0004ff, #ff6600);
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    .content-container {
        text-align: center;
        background: #0004ff;
        border-radius: 10px;
        padding: 20px;
        width: 80%;
        max-width: 800px;
        max-height: 80vh;
        overflow-y: auto;
    }

    h1 {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        color: #ffffff;
        font-weight: bold;
        font-size: 38px;
    }

    p {
        color: #333;
        font-size: 18px;
        margin-top: 20px;
    }

    form {
        width: 100%;
        max-width: 600px;
        margin: 0 auto;
        padding: 20px;
    }

    table {
        width: 100%;
        border-collapse: collapse;
    }

    th, td {
        padding: 10px;
        text-align: left;
    }

    th {
        background-color: #0004ff;
        color: #ffffff;
    }

    input[type="text"],
    input[type="number"] {
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #000113; 
        border-radius: 5px;
        background-color: #fff;
        color: #000000; 
        font-size: 16px;
    }

    input[type="submit"] {
        background-color: #ff6600;
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
        font-size: 18px;
        transition: background-color 0.3s ease;
    }

    input[type="submit"]:hover {
        background-color: #b84b01; 
    }
</style>


<div class="content-container">
<h1>Edit Item</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Edit Item"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}

<style>
    body {
        background: linear-gradient(135deg, #0004ff, #ff6600);
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        margin: 0;
    }

    .login-container {
        text-align: center;
    }

    .login {
        width: 300px;
        padding: 20px;
        border: none;
        border-radius: 10px;
        background: rgba(255, 255, 255, 0.95);
        box-shadow: 0 5px 15px rgba(0, 0, 0, 0.3);
        text-align: center;
    }

    .form-control {
        width: 100%;
        padding: 10px;
        margin-bottom: 15px;
        border: 1px solid #0004ff; /* Blue border */
        border-radius: 5px;
        background-color: #fff;
        color: #333;
        font-size: 16px;
        transition: border-color 0.3s ease;
    }

    .form-control:focus {
        border-color: #0104a3; /* Darker blue when focused */
    }

    .log {
        margin-bottom: 20px;
        color: #0004ff;
        font-weight: bold;
    }

    .login_btn {
        background-color: #0004ff;
        color: #fff;
        border: none;
        padding: 12px 20px;
        border-radius: 5px;
        cursor: pointer;
        font-size: 18px;
        transition: background-color 0.3s ease;
    }

    .login_btn:hover {
        background-color: #0104a3;
    }

    .error-message {
        color: #ff0000; /* Red for error messages */
        margin-top: 10px;
        font-size: 14px;
    }

    .title {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        font-weight: bold;
        color: #ffffff;
        margin-bottom: 20px;
        font-size: 50px;
        letter-spacing: 2px;
    }

    a {
        color: #060858;
        text-decoration: none;
        transition: color 0.3s ease;
    }

    a:hover {
        color: #010d43dc;
    }

    
    .upd {
        color: #0004ff;
    }
</style>
</style>


<div class="login-container">
    <h1 class="title">ZUMART</h1>
    
    <div class="login">
        <h2 class="log">Login</h2>

        <form method="POST" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td class="log">Username: </td>
                    <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                </tr>
                        
                <tr>
                    <td class="log">Password: </td>
                    <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                </tr>

                <tr>
                    <td></td>
                    <td><input class="btn login_btn" type="submit" value="Login"></td>
                </tr>
            </table>
        </form>

        {% if messages %}
            <ul class="error-message">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
            
        <p class="upd">Don't have an account yet? <a class="z"href="{% url 'main:register' %}">Register Now</a></p>
    </div>
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}

<style>
      body {
        background: linear-gradient(135deg, #0004ff, #ff6600);
        display: flex;
        flex-direction: column;
        align-items: center;
        min-height: 100vh;
    }

    nav {
        background-color: #0004ff; 
        color: #fff;
        width: 100%;
        padding: 10px 0;
        display: flex;
        justify-content: space-between;
        align-items: center;
    }

    nav ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        text-align: center;
    }

    nav li {
        display: inline;
        margin-right: 20px;
    }

    nav a {
        color: #fff;
        text-decoration: none;
        font-weight: bold;
        font-size: 18px;
    }

    nav a:hover {
        color: #0f66c3; 
    }

    .user-name {
        margin-right: 20px;
        font-size: 18px;
    }

    .logout-button {
        color: #ffffff; 
        margin-right: 20px;
        border: none;
        cursor: pointer;
        font-size: 18px;
        transition: background-color 0.3s ease;
    }

    .logout-button:hover {
        background-color: #0205a5d5; 
        color: #fff;
    }

    .content-container {
        text-align: center;
        padding: 20px;
        width: 100%;
        max-width: 1000px;
        border-radius: 10px;
        padding: 20px;
        width: 80%;
        max-width: 1000px;
        }


    h1 {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        color: #ffffff;
        font-weight: bold;
        font-size: 58px;
        margin-bottom: 40px;
    }

    h2 {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        color: #0004ff;
        font-weight: bold;
        font-size: 58px;
        margin-bottom: 40px;
    }

    h5 {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        color: rgb(244, 244, 244);
        margin-top: 10px;
        margin-bottom: 20px;
        font-size: 18px;
    }

    p {
        color: rgb(255, 252, 252);
        font-size: 10px;
        margin-top: 20px;
    }

    a {
        color: #0004ff;
        text-decoration: none;
        transition: color 0.3s ease;
    }

    a:hover {
        color: #0057b3;
    }

 
    .card-item {
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
        grid-gap: 20px;
        justify-content: center;
    }

    .card {
        border: none;
        background: #fff;
        border-radius: 10px;
        box-shadow: 0 10px 20px rgba(0, 0, 0, 0.2);
        transition: transform 0.2s;
    }

    .card:hover {
        transform: translateY(-5px);
    }

    .card-title {
        font-size: 20px;
        font-weight: bold;
        color: #0004ff;
        margin-bottom: 10px;
    }

    .card-text {
        font-size: 16px;
        color: #333;
        margin-top: 5px;
    }

    .btn-edit-delete {
        display: flex;
        justify-content: space-between;
        margin-top: 10px;
    }

    .btn-edit-delete a,
    .btn-edit-delete button {
        text-decoration: none;
        padding: 8px 16px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-weight: bold;
        transition: background-color 0.3s ease, color 0.3s ease;
    }

    .btn-edit-delete a {
        background-color: #0004ff;
        color: #fff;
    }

    .btn-edit-delete a:hover {
        background-color: #0104a3;
    }

    .btn-edit-delete button {
        background-color: #ff6600;
        color: #fff;
    }

    .btn-edit-delete button:hover {
        background-color: #800202;
    }
</style>

</style>

<nav>
    <ul>
        <li><a href="#">Beranda</a></li>
        <li><a href="#">Tentang Kami</a></li>
        <li><a href="#">Produk</a></li>
        <li><a href="#">Kontak</a></li>
    </ul>
    <div class="user-info">
        <span class="user-name">{{name}}</span>
        <a href="{% url 'main:logout' %}" class="logout-button">Logout</a>
    </div>
</nav>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h2>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="col-form-label">Name:</label>
                        <input type="text" class="form-control" id="name" name="name"></input>
                    </div>
                    <div class="mb-3">
                        <label for="size" class="col-form-label">Size:</label>
                        <input type="number" class="form-control" id="size" name="size"></input>
                    </div>
                    <div class="mb-3">
                        <label for="size" class="col-form-label"> Color:</label>
                        <input type="text" class="form-control" id="color" name="color"></input>
                    </div>
                    <div class="mb-3">
                        <label for="size" class="col-form-label">Amount:</label>
                        <input type="number" class="form-control" id="amount" name="amount"></input>
                    </div>
                    <div class="mb-3">
                        <label for="price" class="col-form-label">Price:</label>
                        <input type="number" class="form-control" id="price" name="price"></input>
                    </div>
                    <div class="mb-3">
                        <label for="description" class="col-form-label">Description:</label>
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Item</button>
            </div>
        </div>
    </div>
</div>

</body>

<div class="content-container">
    <h1>ZUMART</h1>
    <h5>Menampilkan {{ item_count }} barang {{name}}.</h5>

    <div class="card-item" id="product-cards">


    </div>

    <script>
        async function getItems() {
            return fetch("{% url 'main:get_item_json' %}").then((res) => res.json());
        }

        async function refreshItems() {
            const products = await getItems();
            const cardContainer = document.getElementById("product-cards");
            cardContainer.innerHTML = "";
    
    
        products.forEach((item) => {
            cardContainer.innerHTML += `
                <div class="card-item">
                    <div class="card mx-auto p-3" style="width: 18rem;">
                        <div class="card-body">
                            <h4 class="card-title">${item.fields.name}</h4>
                            <p class="card-text">Price: ${item.fields.size}</p>
                            <p class="card-text">Price: ${item.fields.color}</p>
                            <p class="card-text">Price: ${item.fields.amount}</p>
                            <p class="card-text">${item.fields.description}</p>
                            <a style="justify-content: baseline;" href='edit-item/${item.pk}' class="btn btn-outline-warning" onclick="editItem(${item.pk})">Edit</a>
                            <button style="justify-content: baseline;" class="btn btn-outline-danger" onclick="deleteItem(${item.pk})">Delete</button>
                        </div>
                    </div>
                </div>`;
        });
        }

    function addItem() {
        fetch("{% url 'main:add_item_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshItems);

        document.getElementById("form").reset();
        return false;
    }
    document.getElementById("button_add").onclick = addItem

    function editItem(itemId) {
        fetch(`{% url 'main:edit_item' 0 %}`.replace("0", itemId), {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(() => {
            refreshItems();
            document.getElementById("form").reset();
        });
        return false;
    }

    function deleteItem(itemId) {
        fetch(`{% url 'main:delete_item' 0 %}`.replace("0", itemId), {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshItems)

        document.getElementById("form").reset()
        return false
    }
   

    refreshItems();
    </script>

    <p>Sesi terakhir login: {{ last_login }}</p>

    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Product</button>
    
    <p class="c">By Aiza Derisyana from PBP C.</p>
</div>

{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}
<style>
    body {
        background: linear-gradient(135deg, #0004ff, #ff6600);
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        margin: 0;
    }

    .login-container {
        text-align: center;
    }

    .login {
        width: 500px;
        padding: 20px;
        border: none;
        border-radius: 10px;
        background: rgba(255, 255, 255, 0.95);
        box-shadow: 0 5px 15px rgba(0, 0, 0, 0.3);
        text-align: center;
        margin: 0 auto;
    }

    .form-control {
        width: 100%;
        padding: 10px;
        margin-bottom: 15px;
        border: 1px solid #0004ff; /* Blue border */
        border-radius: 5px;
        background-color: #fff;
        color: #333;
        font-size: 16px;
        transition: border-color 0.3s ease;
    }

    .form-control:focus {
        border-color: #0104a3; /* Darker blue when focused */
    }

    .login_btn {
        background-color: #0004ff;
        color: #fff;
        border: none;
        padding: 12px 20px;
        border-radius: 5px;
        cursor: pointer;
        font-size: 18px;
        transition: background-color 0.3s ease;
    }

    .login_btn:hover {
        background-color: #0104a3;
    }

    .error-message {
        color: #ff0000; /* Red for error messages */
        margin-top: 10px;
        font-size: 14px;
    }

    .title {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        font-weight: bold;
        color: #0004ff;
        margin-bottom: 20px;
        font-size: 40px;
        letter-spacing: 2px;
    }

    a {
        color: #060858;
        text-decoration: none;
        transition: color 0.3s ease;
    }

    a:hover {
        color: #010d43dc;
    }

    .upd {
        color: #0004ff;
    }
</style>

<div class="login-container">
    <div class="login">
        <h1 class="title">Register</h1>
        <form method="POST" class="r">
            {% csrf_token %}
            {{ form.as_table }}
            <input type="submit" class="login_btn" name="submit" value="Daftar" />
        </form>
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li class="error-message">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>
</body>
</html>
{% endblock content %}